language: go

sudo: false

branches:
  except:
    # skip master build, we are building edge and tag that is enough for
    # consistenty check and release. 
    # Let's use Travis CI resources optimally for aah framework.
    - master

go:
  - 1.11.x
  - tip

go_import_path: aahframe.work/cli

install:
  - export GO111MODULE=on
  - cd aah

script:
  - bash <(curl -s https://aahframework.org/go-test)

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  skip_cleanup: true
  script: curl -s https://aahframework.org/publish-cli | bash
  on:
    tags: true

matrix:
  allow_failures:
    - go: tip
